COMMON_FLAGS="-O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

MAKEOPTS="-j__MAKEOPTS__"

LC_MESSAGES=C
FEATURES="${FEATURES} getbinpkg"
USE="-systemd -gnome -kde__GLOBAL_USE_EXTRA__"
